app.name=UniVote
app.version=0.1.0
app.window.title=UniVote | Participación universitaria
app.window.min-width=1024
app.window.min-height=680
app.window.initial-width=1280
app.window.initial-height=800
